import { FormEvent, useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { BookOpen, Check, MoreHorizontal, Pencil, Plus, Search, Trash2, X } from 'lucide-react';
import { getListMemoriesQueryKey, useCreateMemory, useDeleteMemory, useListMemories, useUpdateMemory } from '@workspace/api-client-react';
import { EmptyState, ErrorState, LoadingState, PageIntro } from '@/components/workspace-shell';
import { formatRelativeDate } from '@/lib/format';

type FormState = { title: string; content: string; kind: string; importance: number };
const blank: FormState = { title: '', content: '', kind: 'preference', importance: 3 };

export default function MemoryPage() {
  const queryClient = useQueryClient();
  const memories = useListMemories();
  const create = useCreateMemory();
  const update = useUpdateMemory();
  const remove = useDeleteMemory();
  const [search, setSearch] = useState('');
  const [form, setForm] = useState<FormState>(blank);
  const [editing, setEditing] = useState<number | null>(null);
  const [showForm, setShowForm] = useState(false);
  const [error, setError] = useState('');
  const visible = (memories.data ?? []).filter((memory) => `${memory.title} ${memory.content} ${memory.kind}`.toLowerCase().includes(search.toLowerCase()));

  const close = () => { setShowForm(false); setEditing(null); setForm(blank); setError(''); };
  const submit = (event: FormEvent) => {
    event.preventDefault();
    if (!form.title.trim() || !form.content.trim()) { setError('Give this memory a title and a useful note.'); return; }
    const data = { title: form.title.trim(), content: form.content.trim(), kind: form.kind, importance: Number(form.importance) };
    const onDone = () => { queryClient.invalidateQueries({ queryKey: getListMemoriesQueryKey() }); close(); };
    if (editing) update.mutate({ id: editing, data }, { onSuccess: onDone, onError: () => setError('Could not update this memory.') });
    else create.mutate({ data }, { onSuccess: onDone, onError: () => setError('Could not save this memory.') });
  };

  return <div>
    <PageIntro eyebrow="Persistent context" title="Memory" description="A quiet, durable layer of context for the Companion. Keep what will still matter next week." action={<button onClick={() => { setForm(blank); setEditing(null); setShowForm(true); }} className="flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-semibold text-primary-foreground shadow-sm transition hover:-translate-y-0.5" data-testid="button-add-memory"><Plus size={16} /> Add memory</button>} />
    {showForm && <div className="mb-6 rounded-2xl border border-primary/20 bg-card p-5 shadow-[0_12px_35px_rgba(35,56,66,.07)]"><div className="mb-5 flex items-center justify-between"><h2 className="font-display text-xl font-semibold tracking-[-.03em]">{editing ? 'Edit memory' : 'New memory'}</h2><button onClick={close} className="rounded-lg p-2 text-muted-foreground hover:bg-muted" aria-label="Close memory form" data-testid="button-close-memory-form"><X size={17} /></button></div><form onSubmit={submit} className="grid gap-4 md:grid-cols-[1fr_180px]"><label className="block"><span className="mb-1.5 block text-xs font-semibold">Title</span><input value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder="e.g. Preferred working rhythm" className="w-full rounded-xl border border-input bg-background px-3 py-2.5 text-sm outline-none focus:border-primary" data-testid="input-memory-title" /></label><label className="block"><span className="mb-1.5 block text-xs font-semibold">Kind</span><select value={form.kind} onChange={(event) => setForm({ ...form, kind: event.target.value })} className="w-full rounded-xl border border-input bg-background px-3 py-2.5 text-sm outline-none focus:border-primary" data-testid="select-memory-kind"><option value="preference">Preference</option><option value="project">Project</option><option value="context">Context</option><option value="principle">Principle</option></select></label><label className="block md:col-span-2"><span className="mb-1.5 block text-xs font-semibold">What should the Companion remember?</span><textarea value={form.content} onChange={(event) => setForm({ ...form, content: event.target.value })} rows={3} placeholder="Write the specific context that should shape future work." className="w-full resize-none rounded-xl border border-input bg-background px-3 py-2.5 text-sm leading-6 outline-none focus:border-primary" data-testid="input-memory-content" /></label><div className="flex items-center gap-4 md:col-span-2"><label className="flex items-center gap-3 text-xs font-semibold">Importance <input type="range" min="1" max="5" value={form.importance} onChange={(event) => setForm({ ...form, importance: Number(event.target.value) })} className="accent-primary" data-testid="input-memory-importance" /><span className="font-mono-app text-muted-foreground">{form.importance}/5</span></label><div className="ml-auto flex items-center gap-2"><button type="button" onClick={close} className="rounded-xl px-3 py-2 text-xs font-semibold text-muted-foreground hover:bg-muted" data-testid="button-cancel-memory">Cancel</button><button type="submit" disabled={create.isPending || update.isPending} className="flex items-center gap-2 rounded-xl bg-accent px-4 py-2 text-xs font-bold text-primary disabled:opacity-50" data-testid="button-save-memory"><Check size={14} /> Save memory</button></div></div>{error && <p className="text-xs text-destructive md:col-span-2">{error}</p>}</form></div>}
    <div className="mb-5 flex items-center gap-3 rounded-xl border border-border bg-card px-3 py-2.5"><Search size={16} className="text-muted-foreground" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search your memory..." className="w-full bg-transparent text-sm outline-none placeholder:text-muted-foreground/70" data-testid="input-search-memory" /><span className="hidden font-mono-app text-[10px] text-muted-foreground sm:inline">{visible.length} notes</span></div>
    {memories.isLoading ? <LoadingState /> : memories.isError ? <ErrorState onRetry={() => memories.refetch()} /> : visible.length === 0 ? <EmptyState icon={BookOpen} title={search ? 'Nothing matches that search.' : 'Your context starts here.'} description={search ? 'Try another phrase or clear the search.' : 'Save preferences, projects, and principles that make future conversations more useful.'} action={!search ? <button onClick={() => setShowForm(true)} className="rounded-xl bg-accent px-4 py-2 text-xs font-bold text-primary" data-testid="button-empty-add-memory">Add your first memory</button> : undefined} /> : <div className="grid gap-3 md:grid-cols-2">{visible.map((memory) => <article key={memory.id} className="group rounded-2xl border border-border bg-card p-5 transition duration-200 hover:-translate-y-0.5 hover:border-primary/25 hover:shadow-[0_12px_28px_rgba(35,56,66,.07)]" data-testid={`card-memory-${memory.id}`}><div className="mb-5 flex items-start justify-between gap-3"><div className="flex items-center gap-2"><span className="rounded-lg bg-accent/35 px-2 py-1 font-mono-app text-[9px] uppercase tracking-[.1em] text-primary">{memory.kind}</span><span className="font-mono-app text-[9px] text-muted-foreground">weight {memory.importance}</span></div><div className="flex gap-1 opacity-0 transition group-hover:opacity-100"><button onClick={() => { setEditing(memory.id); setForm({ title: memory.title, content: memory.content, kind: memory.kind, importance: memory.importance }); setShowForm(true); }} className="rounded-lg p-2 text-muted-foreground hover:bg-muted hover:text-primary" aria-label={`Edit ${memory.title}`} data-testid={`button-edit-memory-${memory.id}`}><Pencil size={14} /></button><button onClick={() => { if (window.confirm('Delete this memory?')) remove.mutate({ id: memory.id }, { onSuccess: () => queryClient.invalidateQueries({ queryKey: getListMemoriesQueryKey() }) }); }} className="rounded-lg p-2 text-muted-foreground hover:bg-destructive/10 hover:text-destructive" aria-label={`Delete ${memory.title}`} data-testid={`button-delete-memory-${memory.id}`}><Trash2 size={14} /></button></div></div><h2 className="font-display text-xl font-semibold tracking-[-.03em]">{memory.title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{memory.content}</p><p className="mt-5 font-mono-app text-[9px] uppercase tracking-[.12em] text-muted-foreground">Updated {formatRelativeDate(memory.updatedAt)}</p></article>)}</div>}
  </div>;
}